### ISSUE TITLE
Undefined variable $body at vendor/imanghafoori/laravel-microscope/src/Analyzers/ClassMethods.php:59

### ISSUE THREAD

**Issue by thyseus** [imanghafoori1/laravel-microscope#124] opened 2021-06-03 12:38 UTC
I get the following output when running `sail artisan check:all`:

(...)
```
Checking for route-less controllers...

   ErrorException 

  Undefined variable $body

  at vendor/imanghafoori/laravel-microscope/src/Analyzers/ClassMethods.php:59
     55▕             $methods[] = [
     56▕                 'name' => $name,
     57▕                 'visibility' => $visibility,
     58▕                 'signature' => $signature,
  ➜  59▕                 'body' => Refactor::toString($body),
     60▕                 'startBodyIndex' => [$charIndex, $i],
     61▕                 'returnType' => $returnType,
     62▕                 'nullable_return_type' => $hasNullableReturnType,
     63▕                 'is_static' => $isStatic,

      +30 vendor frames 
  31  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Do you have any idea where this comes from? I am out of ideas.

I can share additional code of my project when necessary to debug this issue.

Thanks a lot !

**Comment by imanghafoori1** [comment] 2021-06-03 16:43
Hi, Please mention your exact PHP version in CLI (not web server)

**Comment by imanghafoori1** [comment] 2021-06-03 18:30
please try out the latest version, so that you can provide a better report.

**Comment by thyseus** [comment] 2021-06-04 07:57
All checks are working now except for `check:dead_controllers`. It creates an _infinite loop_ showing this message forever until i stop with CTRL-C:

^"""(O_o)   Well, It seems we had some problem parsing the contents of:   (o_O)"
^ "Submit an issue on github: https://github.com/imanghafoori1/microscope"
^ "Send us the content and mention your php version (8.0.5)"
^ """
<?php\n
\n
namespace App\Http\Controllers;\n
\n
use App\Models\Customer;\n
use Illuminate\View\View;\n
use Illuminate\Http\RedirectResponse;\n
use Illuminate\Routing\Redirector;\n
\n
class DashboardController extends Controller\n
{\n
\t/**\n
\t * Display the _main_ dashboard of AMVisor.\n
\t *\n
\t * @psalm-suppress UndefinedMagicPropertyFetch\n
\t * @psalm-suppress PossiblyNullPropertyFetch\n
\t * @psalm-suppress PossiblyNullArgument\n
\t * @psalm-suppress PossiblyNullReference\n
\t */\n
\tpublic function index(Customer $customer, string $month = null): View|RedirectResponse|Redirector\n
\t{\n
\t\t// ensure active_customer_id session parameter is identical to the customer id that is requested.\n
\t\t// redirect to / if not - this route handles it correctly.\n
\t\tif ((session()->get('active_customer_id') != $customer->id)) {\n
\t\t\tCustomerController::setCustomer($customer);\n
\n
\t\t\treturn redirect('/');\n
\t\t}\n
\n
\t\tdashboard()->setMonth($month ?? date('Y-m'));\n
\n
\t\treturn view('dashboard');\n
\t}\n
}\n
"""

Is this infinite loop caused by my code ?
Thanks !

**Comment by imanghafoori1** [comment] 2021-06-04 08:14
I guess this line of code is causing the problem

function index(Customer $customer, string $month = null): View|RedirectResponse|Redirector

since I did not counted on the "|" charachter

**Comment by thyseus** [comment] 2021-06-04 08:27
Ok, i see. As far as i know this is valid php, it means "this function can return A _or_ B _or_ C".
Do you want to make the - by the way - great !!! - laravel-microscope be able to handle this style of return hints ? 
If so - we could close this issue and create another "feature request" for that ?

**Comment by imanghafoori1** [comment] 2021-06-04 08:30
I will fix it today, no big deal.
thanks for the report.

**Comment by thyseus** [comment] 2021-06-04 08:31
thanks for this package! closing issue :)

**Comment by imanghafoori1** [comment] 2021-06-04 08:35
Lets just close it only after it is confirmed to be fixed

**Comment by imanghafoori1** [comment] 2021-06-04 11:46
@thyseus Could you please tryout the dev-master version to see if it works.
After you confirm I tag it as the new version.

**Comment by thyseus** [comment] 2021-06-04 13:50
I can confirm that it works now on my code. Good Job !!!

**Closed** 2021-06-04 14:14 UTC
Labels: feature request, php8
